#!/usr/bin/env bash
# Bootstraps the Terraform remote state backend: separate resource group,
# storage account with blob versioning, and the tfstate container.
#
# This is the ONLY meta-infrastructure NOT managed by Terraform itself
# (chicken-and-egg avoidance — state for the backend would need to live somewhere).
#
# Run AFTER setup-phase3-azure.sh. Idempotent — re-running is safe.

set -euo pipefail

TFVARS_FILE="terraform/environments/dev/terraform.tfvars"

# --- Section: Read values from tfvars ---
# Sourced from setup-phase3-azure.sh. Fail fast if missing.
if [[ ! -f "$TFVARS_FILE" ]]; then
  echo "ERROR: $TFVARS_FILE not found. Run setup-phase3-azure.sh first." >&2
  exit 1
fi

# Parse the simple HCL-style "key = \"value\"" lines. Brittle but adequate
# for our controlled tfvars file; a real parser would be overkill here.
PREFIX=$(grep '^project_prefix'   "$TFVARS_FILE" | cut -d'"' -f2)
SUFFIX=$(grep '^project_suffix'   "$TFVARS_FILE" | cut -d'"' -f2)
LOCATION=$(grep '^location'       "$TFVARS_FILE" | cut -d'"' -f2)
ENVIRONMENT=$(grep '^environment' "$TFVARS_FILE" | cut -d'"' -f2)

BACKEND_RG="${PREFIX}-rg-tfstate"
BACKEND_SA="${PREFIX}tfstate${SUFFIX}"   # no hyphens — storage accounts forbid them
BACKEND_CONTAINER="tfstate"
BACKEND_KEY="${ENVIRONMENT}.tfstate"     # state file name within the container

echo "==> Bootstrapping Terraform backend:"
echo "    Resource group:    $BACKEND_RG"
echo "    Storage account:   $BACKEND_SA"
echo "    Container:         $BACKEND_CONTAINER"
echo "    State key:         $BACKEND_KEY"
echo ""

# --- Section: Create resource group ---
# Tagged so anyone (or future-you) can identify its purpose at a glance.
echo "==> Creating resource group..."
az group create \
  --name "$BACKEND_RG" \
  --location "$LOCATION" \
  --tags purpose=tfstate project="$PREFIX" managed-by=bootstrap \
  --output none
echo "    OK"

# --- Section: Create storage account ---
# Standard_LRS: cheapest tier (~$0.02/GB/month). State files are tiny.
# allow-blob-public-access=false: state can contain secrets, must be private.
# min-tls-version=TLS1_2: enforce modern TLS; legacy versions are deprecated.
# kind=StorageV2: required for blob versioning and modern features.
echo "==> Creating storage account..."
az storage account create \
  --name "$BACKEND_SA" \
  --resource-group "$BACKEND_RG" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --allow-blob-public-access false \
  --min-tls-version TLS1_2 \
  --tags purpose=tfstate managed-by=bootstrap \
  --output none
echo "    OK"

# --- Section: Enable blob versioning ---
# Critical for state recovery. Without this, a corrupt state push is unrecoverable.
# With it, every state mutation creates a versioned blob — point-in-time restore for free.
echo "==> Enabling blob versioning..."
az storage account blob-service-properties update \
  --account-name "$BACKEND_SA" \
  --resource-group "$BACKEND_RG" \
  --enable-versioning true \
  --output none
echo "    OK"

# --- Section: Create the tfstate container ---
# Uses the storage account key implicitly (az fetches it). For a one-time bootstrap
# this is fine; ongoing Terraform operations will use AAD auth (configured in Step 3.4).
echo "==> Creating tfstate container..."
az storage container create \
  --name "$BACKEND_CONTAINER" \
  --account-name "$BACKEND_SA" \
  --output none
echo "    OK"

# --- Section: Grant current user data-plane access to state SA ---
# Required for use_azuread_auth=true backend ops. Subscription Owner gives
# management plane only; blob read/write needs the Storage Blob Data Contributor
# role assigned separately on the data plane.
echo "==> Granting Storage Blob Data Contributor on state SA to current user..."
USER_OBJECT_ID=$(az ad signed-in-user show --query id -o tsv)
SA_RESOURCE_ID=$(az storage account show \
  --name "$BACKEND_SA" \
  --resource-group "$BACKEND_RG" \
  --query id -o tsv)

# Idempotent: check if the assignment already exists before creating.
EXISTING=$(az role assignment list \
  --assignee "$USER_OBJECT_ID" \
  --scope "$SA_RESOURCE_ID" \
  --role "Storage Blob Data Contributor" \
  --query "[].id" -o tsv)

if [[ -n "$EXISTING" ]]; then
  echo "    Role assignment already exists"
else
  az role assignment create \
    --assignee "$USER_OBJECT_ID" \
    --role "Storage Blob Data Contributor" \
    --scope "$SA_RESOURCE_ID" \
    --output none
  echo "    OK — waiting 60s for AAD propagation..."
  sleep 60
fi

# --- Section: Write partial backend configuration ---
# Terraform supports splitting backend config: the resource (azurerm) goes in main.tf
# (committed), and the per-environment values go in a separate file (gitignored).
# This way main.tf doesn't leak subscription-identifying suffixes to public git.
BACKEND_CONFIG_FILE="terraform/environments/dev/backend.conf"
cat > "$BACKEND_CONFIG_FILE" <<EOF
# Auto-generated by scripts/setup-phase3-backend.sh. Gitignored.
# Passed to terraform: terraform init -backend-config=backend.conf
resource_group_name  = "$BACKEND_RG"
storage_account_name = "$BACKEND_SA"
container_name       = "$BACKEND_CONTAINER"
key                  = "$BACKEND_KEY"
use_azuread_auth     = true
EOF

echo ""
echo "==> Wrote $BACKEND_CONFIG_FILE:"
sed 's/^/    /' "$BACKEND_CONFIG_FILE"
echo ""
echo "==> Bootstrap complete."
