#!/usr/bin/env bash
# Confirms Azure login, registers required resource providers,
# generates a globally-unique 4-char project suffix, and writes the
# dev environment's terraform.tfvars.
#
# Run AFTER `az login`. Idempotent — re-running reuses the existing suffix.

set -euo pipefail

# --- Constants ---
PROJECT_PREFIX="rl"
ENVIRONMENT="dev"
LOCATION="australiaeast"
TFVARS_FILE="terraform/environments/dev/terraform.tfvars"

# Resource providers required by Terraform. Most are pre-registered on
# established subscriptions; Microsoft.Databricks usually isn't.
PROVIDERS=(
  "Microsoft.Storage"
  "Microsoft.KeyVault"
  "Microsoft.Databricks"
  "Microsoft.ManagedIdentity"
  "Microsoft.Authorization"
  "Microsoft.Resources"
)

# --- Section: Verify login and confirm subscription ---
echo "==> Verifying Azure login..."
if ! az account show >/dev/null 2>&1; then
  echo "ERROR: not logged in. Run 'az login' first." >&2
  exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
TENANT_ID=$(az account show --query tenantId -o tsv)
USER_NAME=$(az account show --query user.name -o tsv)

echo "  Logged in as:  $USER_NAME"
echo "  Subscription:  $SUBSCRIPTION_NAME"
echo "  Sub ID:        $SUBSCRIPTION_ID"
echo "  Tenant ID:     $TENANT_ID"
echo ""
read -p "Use this subscription? [y/N] " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Aborted. Switch with 'az account set --subscription <name-or-id>' then re-run."
  exit 1
fi

# --- Section: Register resource providers ---
# Registration is idempotent. --wait blocks until state transitions to 'Registered'
# (Microsoft.Databricks can take 1-5 minutes the first time; others are instant).
echo "==> Registering Azure resource providers..."
for provider in "${PROVIDERS[@]}"; do
  STATE=$(az provider show --namespace "$provider" --query registrationState -o tsv 2>/dev/null || echo "NotFound")
  if [[ "$STATE" == "Registered" ]]; then
    echo "    $provider: already registered"
  else
    echo "    $provider: registering (may take a few minutes)..."
    az provider register --namespace "$provider" --wait
  fi
done

# --- Section: Generate or reuse the project suffix ---
# 4-char lowercase alphanumeric. Used to make storage account and key vault names
# globally unique. Generated ONCE and persisted; never regenerated unless the file
# is deleted (which would orphan existing resources, so don't).
if [[ -f "$TFVARS_FILE" ]] && grep -q "project_suffix" "$TFVARS_FILE"; then
  SUFFIX=$(grep project_suffix "$TFVARS_FILE" | cut -d'"' -f2)
  echo "==> Reusing existing project suffix: $SUFFIX"
else
  # openssl avoids the head/pipefail SIGPIPE landmine. 2 hex bytes = 4 lowercase chars
  # over [0-9a-f] = 65,536 combinations, ample for global-uniqueness in storage account names.
  SUFFIX=$(openssl rand -hex 2)
  echo "==> Generated new project suffix: $SUFFIX"
fi

# --- Section: Capture developer object ID ---
# Stored so that role assignments for the developer are stable regardless of
# who runs terraform (local user vs CI service principal).
DEVELOPER_OID=$(az ad signed-in-user show --query id -o tsv)
echo "==> Developer object ID: $DEVELOPER_OID"

# --- Section: Write terraform.tfvars ---
mkdir -p "$(dirname "$TFVARS_FILE")"
cat > "$TFVARS_FILE" <<EOF
# Auto-generated by scripts/setup-azure.sh. Gitignored.
# Regenerate on a new machine: re-run the script.
# DO NOT manually edit project_suffix once resources are deployed —
# it would orphan the existing storage account and key vault.

subscription_id = "$SUBSCRIPTION_ID"
tenant_id       = "$TENANT_ID"
project_prefix  = "$PROJECT_PREFIX"
project_suffix  = "$SUFFIX"
environment     = "$ENVIRONMENT"
location        = "$LOCATION"
developer_object_id = "$DEVELOPER_OID"
EOF

echo ""
echo "==> Wrote $TFVARS_FILE:"
sed 's/^/    /' "$TFVARS_FILE"
echo ""
echo "==> Resource naming preview:"
echo "    Resource group:    ${PROJECT_PREFIX}-rg-${ENVIRONMENT}"
echo "    Storage account:   ${PROJECT_PREFIX}st${SUFFIX}"
echo "    Key Vault:         ${PROJECT_PREFIX}-kv-${SUFFIX}"
echo "    Databricks:        ${PROJECT_PREFIX}-dbx-${SUFFIX}"
echo "    Access Connector:  ${PROJECT_PREFIX}-ac-${SUFFIX}"
