# Input variables for the dev environment.
#
# Values come from terraform.tfvars (auto-loaded) which was generated by
# scripts/setup-phase3-azure.sh. The committed terraform.example.tfvars
# documents the shape.

variable "subscription_id" {
  type        = string
  description = "Azure subscription ID for all resources in this environment."

  validation {
    # UUID regex: 8-4-4-4-12 hex chars. Common Terraform validation pattern.
    condition     = can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.subscription_id))
    error_message = "subscription_id must be a valid UUID."
  }
}

variable "tenant_id" {
  type        = string
  description = "Azure Entra ID tenant for authentication."

  validation {
    condition     = can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.tenant_id))
    error_message = "tenant_id must be a valid UUID."
  }
}

variable "project_prefix" {
  type        = string
  description = "Short string used as the prefix for ALL resource names."

  validation {
    condition     = can(regex("^[a-z0-9]{2,4}$", var.project_prefix))
    error_message = "project_prefix must be 2-4 lowercase alphanumeric chars."
  }
}

variable "project_suffix" {
  type        = string
  description = "4-char lowercase alphanumeric suffix used for global-uniqueness of storage account and key vault names."

  validation {
    condition     = can(regex("^[a-z0-9]{4}$", var.project_suffix))
    error_message = "project_suffix must be exactly 4 lowercase alphanumeric chars."
  }
}

variable "environment" {
  type        = string
  description = "One of 'dev', 'test', 'prod'. Used in resource group name and tags."

  validation {
    condition     = contains(["dev", "test", "prod"], var.environment)
    error_message = "environment must be one of 'dev', 'test', 'prod'."
  }
}

variable "location" {
  type        = string
  description = "Azure region. (test CI)"
  default     = "australiaeast"
}

variable "developer_object_id" {
  type        = string
  description = "Azure AD object ID of the developer. Used for granting personal RBAC on KV and storage so it's stable across local-vs-CI runs."

  validation {
    condition     = can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.developer_object_id))
    error_message = "developer_object_id must be a valid UUID."
  }
}
